const wordBank = [
	{en: 'singer', kr: '가수', boolean: false, saved: false, category: 'noun'}, 
	{en: 'first love', kr: '첫사랑', boolean: false, saved: false, category: 'noun'},
	{en: 'gift', kr: '선물', boolean: false, saved: false, category: 'noun'}, 
	{en: 'dragon', kr: '용', boolean: false, saved: false, category: 'noun'},
	{en: 'older brother', kr: '형/오빠', boolean: false, saved: false, category: 'noun'}, 
	{en: 'older sister', kr: '누나/언니', boolean: false, saved: false, category: 'noun'},
	{en: 'job', kr: '직업', boolean: false, saved: false, category: 'noun'}, 
	{en: 'workplace', kr: '회사', boolean: false, saved: false, category: 'noun'},
	{en: 'help', kr: '도와', boolean: false, saved: false, category: 'verb'}, 
	{en: 'bank', kr: '은행', boolean: false, saved: false, category: 'noun'},
	{en: 'receive', kr: '받다', boolean: false, saved: false, category: 'verb'}, 
	{en: 'travel', kr: '여행하다', boolean: false, saved: false, category: 'verb'},
	{en: 'give', kr: '주다', boolean: false, saved: false, category: 'verb'}, 
	{en: 'learn', kr: '배워', boolean: false, saved: false, category: 'verb'},
	{en: 'study', kr: '공부하다', boolean: false, saved: false, category: 'verb'}, 
	{en: 'college', kr: '대학교', boolean: false, saved: false, category: 'noun'},
	{en: 'this year', kr: '올년', boolean: false, saved: false, category: 'noun'}, 
	{en: 'next year', kr: '내년', boolean: false, saved: false, category: 'noun'},
	{en: 'last year', kr: '작년', boolean: false, saved: false, category: 'noun'}, 
	{en: 'meet', kr: '만나다', boolean: false, saved: false, category: 'verb'},
	{en: 'lived', kr: '살아있다', boolean: false, saved: false, category: 'verb'}, 
	{en: 'usually', kr: '보통', boolean: false, saved: false, category: 'adverb'},
	{en: 'and then', kr: '그리고', boolean: false, saved: false, category: 'adverb'}, 
	{en: 'doll', kr: '인형', boolean: false, saved: false, category: 'noun'},
	{en: 'practice', kr: '연습 하다', boolean: false, saved: false, category: 'verb'}, 
	{en: 'send', kr: '보내', boolean: false, saved: false, category: 'verb'},
	{en: 'what a hassle', kr: '귀찮았어', boolean: false, saved: false, category: 'expression'}, 
	{en: 'most', kr: '가장', boolean: false, saved: false, category: 'adverb'},
	{en: 'large', kr: '큰', boolean: false, saved: false, category: 'adjective'}, 
	{en: 'front', kr: '앞', boolean: false, saved: false, category: 'preposition'},
	{en: 'behind', kr: '뒤', boolean: false, saved: false, category: 'preposition'}, 
	{en: 'on top', kr: '위', boolean: false, saved: false, category: 'adjective'},
	{en: 'beneath', kr: '아래/밑', boolean: false, saved: false, category: 'preposition'}, 
	{en: 'next to', kr: '옆', boolean: false, saved: false, category: 'preposition'},
	{en: 'right', kr: '오른쪽', boolean: false, saved: false, category: 'adjective'}, 
	{en: 'left', kr: '왼쪽', boolean: false, saved: false, category: 'adjective'},
	{en: 'middle', kr: '가운대', boolean: false, saved: false, category: 'adjective'}, 
	{en: 'between', kr: '사이', boolean: false, saved: false, category: 'preposition'},
	{en: 'inside', kr: '안', boolean: false, saved: false, category: 'preposition'}, 
	{en: 'outside', kr: '밖', boolean: false, saved: false, category: 'preposition'},
	{en: 'dawn', kr: '새벽', boolean: false, saved: false, category: 'noun'}, 
	{en: 'morning', kr: '아침', boolean: false, saved: false, category: 'noun'},
	{en: 'afternoon', kr: '점심', boolean: false, saved: false, category: 'noun'}, 
	{en: 'evening', kr: '저녁', boolean: false, saved: false, category: 'noun'},
	{en: 'night', kr: '밤', boolean: false, saved: false, category: 'noun'}, 
	{en: 'hometown', kr: '고향', boolean: false, saved: false, category: 'noun'},
	{en: 'only child', kr: '외동 아들', boolean: false, saved: false, category: 'noun'}, 
	{en: 'student', kr: '학생', boolean: false, saved: false, category: 'noun'},
	{en: 'vegetables', kr: '야채', boolean: false, saved: false, category: 'noun'}, 
	{en: 'laugh', kr: '웃기다', boolean: false, saved: false, category: 'verb'}
];

export { wordBank };